#!/usr/bin/expect -f
set timeout 60
set port 65002
set user "u176367625"
set host "46.202.186.144"
set password "23KDHkt10cp$"

spawn ssh -p $port -o StrictHostKeyChecking=no $user@$host
expect "password:"
send "$password\r"
expect "$ "

send "mysql -h 127.0.0.1 -u u176367625_cpagendakt -pu5RjUpN\\\$4/rX u176367625_CPagendaPro -e 'DESCRIBE cp_agenda_users;'\r"
expect "$ "

send "exit\r"
expect eof
