#!/usr/bin/expect -f
set timeout 60
set port 65002
set user "u176367625"
set host "46.202.186.144"
set password "23KDHkt10cp$"

spawn ssh -p $port -o StrictHostKeyChecking=no $user@$host
expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "$ " {
        send "echo 'I AM HERE' > public_html/api/test.txt\r"
        expect "$ "
        send "ls -la public_html/api/test.txt\r"
        expect "$ "
        send "pwd\r"
        expect "$ "
        send "exit\r"
    }
}
expect eof
