#!/usr/bin/expect -f
set timeout 60
set port 65002
set user "u176367625"
set host "46.202.186.144"
set password "23KDHkt10cp$"

spawn ssh -p $port -o StrictHostKeyChecking=no $user@$host
expect "password:"
send "$password\r"
expect "$ "

send "echo 'ROOT' > ~/public_html/test_root.txt\r"
expect "$ "
send "echo 'SUBDIR' > ~/public_html/cpagendapro/test_subdir.txt\r"
expect "$ "
send "echo 'DOMAIN' > ~/domains/creativeprintjp.com/test_domain.txt\r"
expect "$ "

send "exit\r"
expect eof
