#!/usr/bin/expect -f
set timeout 60
set port 65002
set user "u176367625"
set host "46.202.186.144"
set password "23KDHkt10cp$"

spawn ssh -p $port -o StrictHostKeyChecking=no $user@$host
expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "$ " {
        # Login
        send "curl -v -c cookies.txt -X POST -H 'Content-Type: application/json' -d '{\"email\":\"suporte@creativeprintjp.com\",\"password\":\"password1234\"}' https://cpagendapro.creativeprintjp.com/api/auth/login\r"
        expect "$ "
        
        # Get Me
        send "curl -v -b cookies.txt https://cpagendapro.creativeprintjp.com/api/me\r"
        expect "$ "

        # Check Logs
        send "cat domains/creativeprintjp.com/public_html/cpagendapro/api/debug.log\r"
        expect "$ "
        
        send "rm cookies.txt\r"
        send "exit\r"
    }
}
expect eof
