// utils/brazilTimezones.ts
// Maps Brazilian state abbreviations (UF) to their standard IANA timezone identifiers

export const BR_STATE_TIMEZONES: Record<string, string> = {
  SP: 'America/Sao_Paulo',
  RJ: 'America/Sao_Paulo',
  MG: 'America/Sao_Paulo',
  ES: 'America/Sao_Paulo',
  PR: 'America/Sao_Paulo',
  SC: 'America/Sao_Paulo',
  RS: 'America/Sao_Paulo',
  DF: 'America/Sao_Paulo',
  GO: 'America/Sao_Paulo',
  TO: 'America/Araguaina',
  MA: 'America/Fortaleza',
  PI: 'America/Fortaleza',
  CE: 'America/Fortaleza',
  RN: 'America/Fortaleza',
  PB: 'America/Fortaleza',
  PE: 'America/Recife',
  AL: 'America/Maceio',
  SE: 'America/Maceio',
  BA: 'America/Bahia',
  PA: 'America/Belem',
  AP: 'America/Belem',
  AM: 'America/Manaus',
  RR: 'America/Boa_Vista',
  RO: 'America/Porto_Velho',
  MT: 'America/Cuiaba',
  MS: 'America/Campo_Grande',
  AC: 'America/Rio_Branco',
  FN: 'America/Noronha' // Fernando de Noronha
};

export const BR_STATES = [
  { value: 'AC', label: 'Acre (UTC-5)' },
  { value: 'AL', label: 'Alagoas' },
  { value: 'AP', label: 'Amapá' },
  { value: 'AM', label: 'Amazonas (UTC-4)' },
  { value: 'BA', label: 'Bahia' },
  { value: 'CE', label: 'Ceará' },
  { value: 'DF', label: 'Distrito Federal' },
  { value: 'ES', label: 'Espírito Santo' },
  { value: 'GO', label: 'Goiás' },
  { value: 'MA', label: 'Maranhão' },
  { value: 'MT', label: 'Mato Grosso (UTC-4)' },
  { value: 'MS', label: 'Mato Grosso do Sul (UTC-4)' },
  { value: 'MG', label: 'Minas Gerais' },
  { value: 'PA', label: 'Pará' },
  { value: 'PB', label: 'Paraíba' },
  { value: 'PR', label: 'Paraná' },
  { value: 'PE', label: 'Pernambuco' },
  { value: 'PI', label: 'Piauí' },
  { value: 'RJ', label: 'Rio de Janeiro' },
  { value: 'RN', label: 'Rio Grande do Norte' },
  { value: 'RS', label: 'Rio Grande do Sul' },
  { value: 'RO', label: 'Rondônia (UTC-4)' },
  { value: 'RR', label: 'Roraima (UTC-4)' },
  { value: 'SC', label: 'Santa Catarina' },
  { value: 'SP', label: 'São Paulo' },
  { value: 'SE', label: 'Sergipe' },
  { value: 'TO', label: 'Tocantins' },
  { value: 'FN', label: 'Fernando de Noronha (UTC-2)' }
];
